// <auto-generated />
namespace PosDesktop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SyncSchema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncSchema));

        string IMigrationMetadata.Id
        {
            get { return "20260220000100_SyncSchema"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
